direction: down


LawISA: "法律 ISA"
SubjCat: "主体范畴"
IG: "意识形态一般"
NoHist: "没有历史 / 永恒形式"
Imag: "想象关系的表述"
Mat: "物质性: 机器-仪式-实践"
Int: "唤问 → 主体"
Rec: "承认 / 误认"
Auto: "个人自动运转"
RoP: "生产关系再生产"

LawISA -> SubjCat
IG -> NoHist
IG -> Imag
IG -> Mat
IG -> Int
Int -> Rec
Mat -> Auto
Auto -> RoP
