direction: down


Meta: "大厦隐喻"
Need: "需要具体理论"
Law: "法: 形式平等的法人世界"
Gap: "不足以再生产生产关系"
Rep: "镇压性补充"
Ideo: "法律—道德意识形态补充"
ISA: "法律 ISA / 诸 ISA"
RSA: "RSA"

Meta -> Need
Need -> Law
Law -> Gap
Gap -> Rep
Gap -> Ideo
Ideo -> ISA
Rep -> RSA
