direction: down

Row1___: {
  label: "Row1[ ]"
  direction_LR: "direction LR"
  A1: "写使能"
  A2_扇区擦除__--__A3_等待空闲_: "A2[扇区擦除] --> A3[等待空闲]"
}
Row2___: {
  label: "Row2[ ]"
  B1: "写使能"
  B2_页编程__--__B3_等待空闲_: "B2[页编程] --> B3[等待空闲]"
}


Row1___.A1 -> Row1___.A2_扇区擦除__--__A3_等待空闲_
Row2___.B1 -> Row2___.B2_页编程__--__B3_等待空闲_
