direction: down


N: "North"
INST: "Institutions"
PD: "Path Dependence"
M: "Mokyr"
UK: "Useful Knowledge"
TC: "Technological Creativity"
A: "Aghion"
CD: "Creative Destruction"
JP: "Noguchi"
S40: "1940 System"
LD: "Lost Decades"
TV: "Tvede"
BC: "Business Cycles"
Y: "Yin"
PC: "Population and Capital"
SS: "Secular Stagnation"

N -> INST
N -> PD
M -> UK
M -> TC
A -> CD
UK -> CD
INST -> CD
JP -> S40
S40 -> LD
TV -> BC
Y -> PC
LD -> SS
PC -> SS
