direction: right


A: "时钟树"
B: "GPIO 原理"
C: "硬件电路"
D: "定时器"
E: "ADC"
F: "UART 串口"
G: "I2C"
H: "SPI"
I: "MPU6050 / OLED"
J: "W25Q64"
K: "HAL 库"

A -> B
B -> C
C -> D
C -> E
D -> F
E -> F
F -> G
F -> H
G -> I
H -> J
I -> K
J -> K
