direction: right


Epic: "史诗综合体"
Emp: "经验性"
Fic: "虚构性"
Hist: "历史性"
Mim: "摹仿性"
Rom: "传奇性"
Did: "教寓性/寓言"
Novel: "小说综合"
Post: "后小说实验"

Epic -> Emp
Epic -> Fic
Emp -> Hist
Emp -> Mim
Fic -> Rom
Fic -> Did
Hist -> Novel
Mim -> Novel
Rom -> Novel
Did -> Novel
Novel -> Post
