direction: down


D: "梦的解析"
DW: "梦工作"
UC: "无意识"
PEL: "日常生活心理病理学"
TE: "性学三论"
LB: "原欲"
IL: "精神分析引论"
RP: "压抑与抗拒"
TF: "移情"
BP: "超越快乐原则"
EI: "自我与本我"
TT: "图腾与禁忌"
OC: "俄狄浦斯"
Z: "齐泽克/拉康"

D -> DW
D -> UC
PEL -> UC
TE -> LB
IL -> RP
IL -> TF
BP -> EI
TT -> OC
D -> OC
Z -> UC
