direction: down


A: "访问 www.baidu.com"
B: "检查本机 hosts 文件"
C_有无_IP_记录__: "C{有无 IP 记录?}"
C_--_有: "C -- 有"
D: "打开网站"
C_--_无: "C -- 无"
E: "查询 DNS 服务器"
F_DNS_是否有记录__: "F{DNS 是否有记录?}"
F_--_有: "F -- 有"
F_--_无: "F -- 无"
G: "网站不存在"

A -> B
B -> C_有无_IP_记录__
C_--_有 -> D
C_--_无 -> E
E -> F_DNS_是否有记录__
F_--_有 -> D
F_--_无 -> G
