direction: down


MP: "生产方式 = 生产力 ∪ 生产关系"
Cond: "生产条件的再生产"
Mat: "生产资料再生产"
LP: "劳动力再生产"
Skills: "本领 / 技能"
Subj: "对占统治地位意识形态的臣服"
Super: "上层建筑: 法 · 国家"
RSA: "镇压性国家机器 RSA"
ISA: "意识形态国家机器 ISA"
RoP__Reproduction_of_Relations_of_Production__: "RoP[[Reproduction of Relations of Production]]"
RoP: "RoP"
Class: "阶级斗争贯穿一切层级"
Rev: "革命: 打碎并更换机器"

MP -> Cond
Cond -> Mat
Cond -> LP
LP -> Skills
LP -> Subj
Subj -> Super
Super -> RSA
Super -> ISA
ISA -> RoP__Reproduction_of_Relations_of_Production__
RoP -> Class
Class -> Rev
