direction: right


VT: "向量表\nSVC / PendSV / SysTick"
Map: "宏映射或改名"
Port: "port.c\nvPortSVCHandler\nxPortPendSVHandler\nxPortSysTickHandler"
Sched: "调度器"
Map_--__Port_--__Sched: "Map --> Port --> Sched"

VT -> Map_--__Port_--__Sched
