direction: down


C: "Capital"
CF: "Commodity Fetishism"
SV: "Surplus Value"
PA: "Primitive Accumulation"
W: "What Is to Be Done"
E: "Economism"
VP: "Vanguard Party"
O: "One Step Forward"
DC: "Democratic Centralism"
M: "Power and Money"
B: "Bureaucracy"
SUB: "Substitutionism"
SCF: "State Commodity Fetishism"

C -> CF
C -> SV
C -> PA
W -> E
W -> VP
O -> DC
O -> VP
M -> B
M -> SUB
M -> SCF
CF -> SCF
VP -> SUB
