direction: right


Q: "Q 命题知识"
L: "λ 技术"
Y: "产出 / 福利"
Access: "接入成本"
__Q: "> Q"
__L: "> L"
Inst: "制度与文化"
__Access: "> Access"
__Map_Q_λ_映射_: "> Map[Q→λ 映射]"

Q -> L: "epistemic base"
L -> Y: "生产"
Access -> __Q
Access -> __L
Inst -> __Access
Inst -> __Map_Q_λ_映射_
