direction: down


RP: "生产关系"
Repro: "被再生产"
Power: "国家政权"
RSA: "RSA"
ISA: "诸 ISA"
DomIdeo: "占统治地位的意识形态"
School: "学校等装置"
Int: "唤问 → 主体就位"

RP -> Repro: "需要"
Repro -> Power
Power -> RSA
Power -> ISA
ISA -> DomIdeo
DomIdeo -> School
School -> Int
Int -> RP
