direction: down


SF: "Schelling Freedom"
GE: "Ground/Existence"
SH: "Schelling History"
D: "Debord"
SP: "Spectacle"
B: "Baudrillard"
SV: "Sign Value"
A: "Althusser"
ISA: "ISA / Interpellation"
CONS: "Consumption"
N: "Scholes Narrative"
NAR: "Narrative"

SF -> GE
SH -> GE
D -> SP
B -> SV
A -> ISA
SP -> CONS
SV -> CONS
N -> NAR
